def countNucleotides(seqs):
    baseCount = { 'A':0, 'C':0, 'G':0, 'T':0 }
    for i in range(len(seqs)):
        baseCount[seqs[i]] += 1
        values = baseCount.values()
        listValues = list(values)
    return print(*listValues)

seqsss = 'TTCCATCGCTTGCTGGTTAGTGCAAGTATCTGACCTTGTGTAACTGATGTAAGCCCACGCGAAAGGTCCAACATGTGACGCGCCCGCAGGCTATCCTCTCTTAAAGGAGTTCGGGACTAAAGGGGACTAAGTGTCATCCGGATGGTCCCGACTCGGTTTTCGATGTGAGCTGGTTCGACCGGTCGGCAATTCGTCCACCTAGTCTAAGCACGAATTCACCGTTTTTGTGCAGGAGCACCCACGACAAGATCAATAACTCGTTTTCCATGGGATGGGAAATCAGCCGCGAAACGATTCCTGAACCACGGAGCGGATCCCTCGTAAAAGGCAGGTCCGAGGCGAGACTAACAATATTGTGTTTTGTAATAGAGAACTTGGAGTTCTCGCGTATATTAGCACGTCGCATTGCACTCAGTTCTGTTGGCAAGACTGGTTTCCATATCGCCGGTTAAGCACCTCGGGAACGCGAACTGACTGTGAGCCATGACATAGCGGGCAGAGGCCCCGACCAATAAAAGCTCGGCGGACTTTATCACTAAATACTAACGGAAAATGATAAACGGTGCGCAGTACCTCAGCGTCAGTGCTGCGCATACTTCATATGTTGGCGCTTAATAAGTGGGAATTATGTGCAATGCTAAATTGCCGACGGGCTATCGTCTGTCCGACAATTGGCGCGCACTATGGCGCACCTGCTCTGTTTCTACACATAACCATTGCTCAATAGTAGTATAAAGTGTTTGCCACCCCTAACCCTCCGTCTCAAGGGTGAAGTATGAGAGTTTTAGTCCTGGGGTTGGAGCGGAATTAGCCAGGGCCG'
countNucleotides(seqsss)